baseURL = "https://ngocdat784.github.io/blog/"
languageCode = "vi"
title = "Ký sự Lập trình Web & JavaScript"
theme = "paper"

relativeURLs = true
canonifyURLs = false

[params]
  description = "Chia sẻ kiến thức Java, JavaScript và lập trình mạng cho sinh viên"

# =========================
# MENU CHÍNH
# =========================

[[menu.main]]
  name = "Trang chủ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "About Me"
  url = "about/"
  weight = 3
